//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsPanel
{
    public partial class Drivers
    {
        protected global::System.Web.UI.WebControls.Button btnDeleteDriver;
        protected global::System.Web.UI.WebControls.HiddenField hfEditDriverId;
        protected global::System.Web.UI.WebControls.Repeater rptDrivers;
        protected global::System.Web.UI.WebControls.PlaceHolder phNoDrivers;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlVehicle;
        protected global::System.Web.UI.WebControls.Button btnSaveDriver;
    }
}
