//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsPanel
{
    public partial class Vehicles
    {
        protected global::System.Web.UI.WebControls.Repeater rptVehicles;
        protected global::System.Web.UI.WebControls.PlaceHolder phNoVehicles;
        protected global::System.Web.UI.WebControls.TextBox txtPlateNumber;
        protected global::System.Web.UI.WebControls.TextBox txtBrand;
        protected global::System.Web.UI.WebControls.TextBox txtModel;
        protected global::System.Web.UI.WebControls.TextBox txtCapacity;
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
        protected global::System.Web.UI.WebControls.Button btnSaveVehicle;
        protected global::System.Web.UI.WebControls.HiddenField hfEditVehicleId;
        protected global::System.Web.UI.WebControls.Button btnDeleteVehicle;
    }
}
